### PR TITLE
#96 Allow edit CurrentDay from external code

### LINKED ISSUE #96: OnInitialized CurrentDay is always today
I would like to set the CurrentDay when loading the calender. And changing it with my code.

I can do a pr myself.

### PR DESCRIPTION
**Pull request by TDroogers**
Fixes #96

### CODE REVIEW

**Comment by danheron** [comment]
Thanks for the pull request.  However I think your changes are more complicated than they need to be.

I have fixed this issue now.  Can you check that my fix does what you need it to?

**Comment by TDroogers** [comment]
#106 Seems fine, I will test it this evening. CurrentDay is in this version indeed a bit to complex.

**Comment by sykesbPragmatics** [comment]
You guys are amazing.  I just ran into this myself and I'm thankful the fix is inbound.

**Comment by TDroogers** [comment]
@danheron Yes #107 does fix my issue as well!

**Pull request closed without merging**
